-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Jeu 25 Juin 2020 à 16:30
-- Version du serveur :  5.6.17
-- Version de PHP :  5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `codflix`
--

-- --------------------------------------------------------

--
-- Structure de la table `genre`
--

CREATE TABLE IF NOT EXISTS `genre` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10771 ;

--
-- Contenu de la table `genre`
--

INSERT INTO `genre` (`id`, `name`) VALUES
(28, 'Action'),
(12, 'Adventure'),
(18, 'Drama'),
(80, 'Crime'),
(53, 'Thriller'),
(36, 'History'),
(10749, 'Romance'),
(35, 'Comedy'),
(14, 'Fantasy'),
(27, 'Horror'),
(878, 'Science Fiction'),
(9648, 'Mystery'),
(37, 'Western'),
(16, 'Animation'),
(10751, 'Family'),
(10752, 'War'),
(10402, 'Music'),
(99, 'Documentary'),
(10770, 'TV Movie');

-- --------------------------------------------------------

--
-- Structure de la table `history`
--

CREATE TABLE IF NOT EXISTS `history` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `media_id` int(11) NOT NULL,
  `start_date` date NOT NULL,
  `finish_date` date NOT NULL,
  `watch_duration` mediumint(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Structure de la table `media`
--

CREATE TABLE IF NOT EXISTS `media` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `genre_id` int(20) NOT NULL,
  `title` varchar(20) NOT NULL,
  `picture` varchar(400) DEFAULT NULL,
  `type` varchar(20) NOT NULL,
  `status` varchar(40) NOT NULL,
  `release_date` date NOT NULL,
  `vote_count` int(11) NOT NULL,
  `vote_avertage` int(11) NOT NULL,
  `summary` varchar(255) NOT NULL,
  `runtime` int(11) NOT NULL,
  `trailer_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=151 ;

--
-- Contenu de la table `media`
--

INSERT INTO `media` (`id`, `genre_id`, `title`, `picture`, `type`, `status`, `release_date`, `vote_count`, `vote_avertage`, `summary`, `runtime`, `trailer_url`) VALUES
(1, 18, 'Varjoja paratiisissa', 'https://image.tmdb.org/t/p/w500//jMmHFm0TcjiN9QDICXY2tJcQsDl.jpg', 'movie', 'Released', '1986-10-17', 112, 7, 'An episode in the life of Nikander, a garbage man, involving the death of a co-worker, an affair and much more.', 72, ''),
(2, 28, 'Judgment Night', 'https://image.tmdb.org/t/p/w500//5aXp2s4l6g5PcMMesIj63mx8hmJ.jpg', 'movie', 'Released', '1993-10-15', 150, 6, 'While racing to a boxing match, Frank, Mike, John and Rey get more than they bargained for. A wrong turn lands them directly in the path of Fallon, a vicious, wise-cracking drug lord. After accidentally witnessing Fallon murder a disloyal henchman, the fo', 110, ''),
(3, 99, 'Life in Loops (A Meg', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2006-01-01', 11, 8, 'Timo Novotny labels his new project an experimental music documentary film, in a remix of the celebrated film Megacities (1997), a visually refined essay on the hidden faces of several world "megacities" by leading Austrian documentarist Michael Glawogger', 80, ''),
(4, 18, 'Sonntag im August', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2004-09-02', 6, 7, '', 15, ''),
(5, 12, 'Star Wars', 'https://image.tmdb.org/t/p/w500//zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg', 'movie', 'Released', '1977-05-25', 13850, 8, 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beauti', 121, ''),
(6, 35, 'Forrest Gump', 'https://image.tmdb.org/t/p/w500//7c9UVPPiTPltouxRVY6N9uugaVA.jpg', 'movie', 'Released', '1994-07-06', 18263, 8, 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 142, ''),
(7, 9648, 'Citizen Kane', 'https://image.tmdb.org/t/p/w500//apbg31SYrIx7dsTJNrAhQWsWdEM.jpg', 'movie', 'Released', '1941-04-17', 3146, 8, 'Newspaper magnate, Charles Foster Kane is taken from his mother as a boy and made the ward of a rich industrialist. As a result, every well-meaning, tyrannical or self-destructive move he makes for the rest of his life appears in some way to be a reaction', 119, ''),
(8, 27, 'The Dark', 'https://image.tmdb.org/t/p/w500//7PTtdFO5sphcc91e7X3NUgE46dq.jpg', 'movie', 'Released', '2005-09-28', 168, 6, 'Adèle and her daughter Sarah are traveling on the Welsh coastline to see her husband James when Sarah disappears. A different but similar looking girl appears who says she died in a past time. Adèle tries to discover what happened to her daughter as she i', 87, ''),
(9, 12, 'The Fifth Element', 'https://image.tmdb.org/t/p/w500//wgvc3PmjQGtYYDWaeuV867mnFDs.jpg', 'movie', 'Released', '1997-05-02', 7377, 8, 'In 2257, a taxi driver is unintentionally given the task of saving a young girl who is part of the key that will ensure the survival of humanity.', 126, ''),
(10, 18, 'My Life Without Me', 'https://image.tmdb.org/t/p/w500//kZyurQjTMLHalUxs7sHgH5XeiwO.jpg', 'movie', 'Released', '2003-03-07', 256, 6, 'A fatally ill mother with only two months to live creates a list of things she wants to do before she dies without telling her family of her illness.', 106, ''),
(11, 28, 'Kill Bill: Vol. 1', 'https://image.tmdb.org/t/p/w500//iffzIhuLAO38Po6sh1s6ZEVwlNL.jpg', 'movie', 'Released', '2003-10-10', 11877, 8, 'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle – but she lives to plot her vengeance.', 111, ''),
(12, 18, 'Jarhead', 'https://image.tmdb.org/t/p/w500//38tSutxTmkWJswHeX6SOCI7bKW9.jpg', 'movie', 'Released', '2005-11-04', 1716, 7, 'Jarhead is a film about a US Marine Anthony Swofford’s experience in the Gulf War. After putting up with an arduous boot camp, Swofford and his unit are sent to the Persian Gulf where they are eager to fight, but are forced to stay back from the action. S', 123, ''),
(13, 18, 'Apocalypse Now', 'https://image.tmdb.org/t/p/w500//9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg', 'movie', 'Released', '1979-08-15', 5005, 8, 'At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, "does not exist, nor will it ever exist." His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been', 147, ''),
(14, 16, '彼女の想いで', 'https://image.tmdb.org/t/p/w500//1T8EKJ1zTzAsk48PLxq5ev7ZuQx.jpg', 'movie', 'Released', '1995-12-23', 87, 4, 'Koji Morimato’s animated science fiction short story about how the border between reality and illusion on a space station becomes blurry.', 44, ''),
(15, 28, '最臭兵器', 'https://image.tmdb.org/t/p/w500//mabl2ejycTB7KiZnCsd6w8oPHIT.jpg', 'movie', 'Released', '1995-12-23', 8, 7, 'Tensai Okamura’s animated action packed short story with lots of humorous elements in which a person transforms into a weapon of mass destruction without themselves being aware.', 40, ''),
(16, 16, '大砲の街', 'https://image.tmdb.org/t/p/w500//bc6xbP8UjH1sVMksFrI0DwoS0yr.jpg', 'movie', 'Released', '1995-12-23', 10, 7, 'Otomo Katsuhiro’s short anime story', 21, ''),
(17, 37, 'Unforgiven', 'https://image.tmdb.org/t/p/w500//7O3ocR8n2ItqIgcxE1CY8ZHTJsz.jpg', 'movie', 'Released', '1992-08-07', 2443, 8, 'William Munny is a retired, once-ruthless killer turned gentle widower and hog farmer. To help support his two motherless children, he accepts one last bounty-hunter mission to find the men who brutalized a prostitute. Joined by his former partner and a c', 131, ''),
(18, 878, 'Eternal Sunshine of ', 'https://image.tmdb.org/t/p/w500//nh6YJdN7C66IMckrAM5WJ6Ycrhf.jpg', 'movie', 'Released', '2004-03-19', 9509, 8, 'Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.', 108, ''),
(19, 18, 'Amores perros', 'https://image.tmdb.org/t/p/w500//eOjRuLQ7ChUNKeKyCZV5j94MkPQ.jpg', 'movie', 'Released', '2000-06-16', 1360, 8, 'A fatalistic car crash in Mexico City sets off a chain of events in the lives of three persons: a young man aching to run off with his sister-in-law, a supermodel, and a homeless man. Their lives are catapulted into unforeseen circumstances instigated by ', 154, ''),
(20, 18, 'A History of Violenc', 'https://image.tmdb.org/t/p/w500//b6zLmqCKUFBqrc9zmMVT50YWhjK.jpg', 'movie', 'Released', '2005-09-23', 1858, 7, 'An average family is thrust into the spotlight after the father commits a seemingly self-defense murder at his diner.', 96, ''),
(21, 18, 'Hable con ella', 'https://image.tmdb.org/t/p/w500//oJrOrkFd32Zau6HYZ4jJprqhzlc.jpg', 'movie', 'Released', '2002-03-14', 693, 8, 'Two men share an odd friendship while they care for two women who are both in deep comas.', 112, ''),
(22, 18, '8 Mile', 'https://image.tmdb.org/t/p/w500//bfccQmQWNFQYRv4PHgCnjDu7PXn.jpg', 'movie', 'Released', '2002-11-08', 4476, 7, 'The setting is Detroit in 1995. The city is divided by 8 Mile, a road that splits the town in half along racial lines. A young white rapper, Jimmy "B-Rabbit" Smith Jr. summons strength within himself to cross over these arbitrary boundaries to fulfill his', 110, ''),
(23, 80, 'Absolute Power', 'https://image.tmdb.org/t/p/w500//n7U0FEirHej1yQIy2mAzDtF9wBz.jpg', 'movie', 'Released', '1997-02-14', 550, 7, 'A master thief coincidentally is robbing a house where a murder—in which the President of The United States is involved—occurs in front of his eyes. He is forced to run, while holding evidence that could convict the President.', 121, ''),
(24, 53, 'Paradise Now', 'https://image.tmdb.org/t/p/w500//pIESejTZpHXvc6SF0LuQWpJIUD2.jpg', 'movie', 'Released', '2005-02-14', 138, 7, 'From the perspective of two Palestinian men who are preparing to perform a suicide attack in Israel, this is the first film to deal with the subject of suicide bombers.', 90, ''),
(25, 35, 'Brazil', 'https://image.tmdb.org/t/p/w500//ziRWOYnl6e2JUaHYmFLR1kfcECM.jpg', 'movie', 'Released', '1985-02-20', 2006, 8, 'Low-level bureaucrat Sam Lowry escapes the monotony of his day-to-day life through a recurring daydream of himself as a virtuous hero saving a beautiful damsel. Investigating a case that led to the wrongful arrest and eventual death of an innocent man ins', 132, ''),
(26, 12, 'War of the Worlds', 'https://image.tmdb.org/t/p/w500//kJ5w8LEByIUCXus7mUADIs00cR8.jpg', 'movie', 'Released', '2005-06-28', 5443, 6, 'Ray Ferrier is a divorced dockworker and less-than-perfect father. Soon after his ex-wife and her new husband drop off his teenage son and young daughter for a rare weekend visit, a strange and powerful lightning storm touches down.', 116, ''),
(27, 18, 'Before Sunrise', 'https://image.tmdb.org/t/p/w500//qA2TyqPldTtoTVY3LKrNIG5g6bH.jpg', 'movie', 'Released', '1995-01-27', 2316, 8, 'On his way to Vienna, American Jesse meets Céline, a student returning to Paris. After long conversations forge a surprising connection between them, Jesse convinces Celine to get off the train with him in Vienna. Since his flight to the U.S. departs the ', 101, ''),
(28, 878, 'Blade Runner', 'https://image.tmdb.org/t/p/w500//eIi3klFf7mp3oL5EEF4mLIDs26r.jpg', 'movie', 'Released', '1982-06-25', 9218, 8, 'In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.', 118, ''),
(29, 18, '英雄', 'https://image.tmdb.org/t/p/w500//p31yIpOO7VLP9lJa3YH0sLX9q3H.jpg', 'movie', 'Released', '2002-07-22', 1320, 8, 'One man defeated three assassins who sought to murder the most powerful warlord in pre-unified China.', 99, ''),
(30, 18, 'Before Sunset', 'https://image.tmdb.org/t/p/w500//90MdQTVdjso5J35xPurGC6M2Tma.jpg', 'movie', 'Released', '2004-02-10', 1902, 8, 'Nine years ago two strangers met by chance and spent a night in Vienna that ended before sunrise. They are about to meet for the first time since. Now they have one afternoon to find out if they belong together.', 80, ''),
(31, 12, '風の谷のナウシカ', 'https://image.tmdb.org/t/p/w500//ulVUa2MvnJAjAeRt7h23FFJVRKH.jpg', 'movie', 'Released', '1984-03-11', 1955, 8, 'After a global war, the seaside kingdom known as the Valley of the Wind remains one of the last strongholds on Earth untouched by a poisonous jungle and the powerful insects that guard it. Led by the courageous Princess Nausicaä, the people of the Valley ', 117, ''),
(32, 28, 'Miami Vice', 'https://image.tmdb.org/t/p/w500//wJMw7l0H4FaGCaF0ldkU2wPhd1E.jpg', 'movie', 'Released', '2006-07-27', 1042, 6, 'A case involving drug lords and murder in South Florida takes a personal turn for undercover detectives Sonny Crockett and Ricardo Tubbs. Unorthodox Crockett gets involved romantically with the Chinese-Cuban wife of a trafficker of arms and drugs, while T', 132, ''),
(33, 18, 'Open Water', 'https://image.tmdb.org/t/p/w500//58BUQzjN6TH0bLe6JEfgMbHc55u.jpg', 'movie', 'Released', '2003-12-29', 681, 5, 'Two divers are left out at sea without a boat. There’s nothing but water for miles, unless they look at what’s underneath them...', 79, ''),
(34, 12, 'Raiders of the Lost ', 'https://image.tmdb.org/t/p/w500//kCiMExsYuNhYluHxPP2OTmWw7hp.jpg', 'movie', 'Released', '1981-06-12', 8060, 8, 'When Dr. Indiana Jones – the tweed-suited professor who just happens to be a celebrated archaeologist – is hired by the government to locate the legendary Ark of the Covenant, he finds himself up against the entire Nazi regime.', 115, ''),
(35, 12, 'Indiana Jones and th', 'https://image.tmdb.org/t/p/w500//iO73omOyLwUPW22EpaZkJNC72ec.jpg', 'movie', 'Released', '1984-05-23', 5929, 7, 'After arriving in India, Indiana Jones is asked by a desperate village to find a mystical stone. He agrees – and stumbles upon a secret cult plotting a terrible plan in the catacombs of an ancient palace.', 118, ''),
(36, 99, 'Las Hurdes', 'https://image.tmdb.org/t/p/w500//aaRbO3m3L3yVg2L73QLYvgP23hj.jpg', 'movie', 'Released', '1933-12-01', 77, 7, 'An exploration —manipulated and staged— of life in Las Hurdes, in the province of Cáceres, in Extremadura, Spain, as it was in 1932. Insalubrity, misery and lack of opportunities provoke the emigration of young people and the solitude of those who remain ', 29, ''),
(37, 99, 'Megacities', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '1998-08-12', 7, 8, 'Megacities is a documentary about the slums of five different metropolitan cities.', 94, ''),
(38, 35, 'Kunstgriff', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2002-01-01', 1, 10, 'Kunstgriff is a brilliantly filmed black and white short film. Andre F. Nebe gives proof of his storytelling abilities in this 6 minute film.', 6, ''),
(39, 35, 'Lock, Stock and Two ', 'https://image.tmdb.org/t/p/w500//tY6zVyt0OubPgCapbXFJLKhQqSu.jpg', 'movie', 'Released', '1998-03-05', 4025, 8, 'A card shark and his unwillingly-enlisted friends need to make a lot of cash quick after losing a sketchy poker match. To do this they decide to pull a heist on a small-time gang who happen to be operating out of the flat next door.', 105, ''),
(40, 18, 'Elsker dig for evigt', 'https://image.tmdb.org/t/p/w500//1pRNzOM7OQA29cVayaCheBI4vn7.jpg', 'movie', 'Released', '2002-09-06', 55, 7, 'Cecilie and Joachim are about to get married when a freak car accident leaves Joachim disabled, throwing their lives into a spin. The driver of the other car, Marie, and her family don’t get off lightly, either. Her husband Niels works in the hospital whe', 113, ''),
(41, 80, 'Taxi Driver', 'https://image.tmdb.org/t/p/w500//a58oc5qGNazb3QOxEH8eG5S7gjr.jpg', 'movie', 'Released', '1976-02-09', 6960, 8, 'A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feed his urge for violent action, attempting to save a preadolescent prostitute in the process.', 114, ''),
(42, 878, 'Predator', 'https://image.tmdb.org/t/p/w500//ymuFO6955B7tNZzwj5XGcsJ8ehh.jpg', 'movie', 'Released', '1987-06-12', 4644, 7, 'Dutch and his group of commandos are hired by the CIA to rescue downed airmen from guerillas in a Central American jungle. The mission goes well but as they return they find that something is hunting them. Nearly invisible, it blends in with the forest, t', 107, ''),
(43, 53, 'Snatch', 'https://image.tmdb.org/t/p/w500//1UnjPqG1d730s135O5tAALt2ted.jpg', 'movie', 'Released', '2000-09-01', 5808, 8, 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.', 103, ''),
(44, 18, 'Trois couleurs : Ble', 'https://image.tmdb.org/t/p/w500//s9rWmLANsVlSV4XmuC0IUcseGzO.jpg', 'movie', 'Released', '1993-01-10', 866, 8, 'Julie is haunted by her grief after living through a tragic auto wreck that claimed the life of her composer husband and young daughter. Her initial reaction is to withdraw from her relationships, lock herself in her apartment and suppress her pain. But a', 98, ''),
(45, 35, 'Trois couleurs : Bla', 'https://image.tmdb.org/t/p/w500//2eBL3wXDZqemW8SJ1RNxqtx6bgJ.jpg', 'movie', 'Released', '1994-01-26', 592, 8, 'Polish immigrant Karol Karol finds himself out of a marriage, a job and a country when his French wife, Dominique, divorces him after six months due to his impotence. Forced to leave France after losing the business they jointly owned, Karol enlists fello', 92, ''),
(46, 28, 'Scarface', 'https://image.tmdb.org/t/p/w500//cCvp5Sni75agCtyJkNOMapORUQV.jpg', 'movie', 'Released', '1983-12-08', 7055, 8, 'After getting a green card in exchange for assassinating a Cuban government official, Tony Montana stakes a claim on the drug trade in Miami. Viciously murdering anyone who stands in his way, Tony eventually becomes the biggest drug lord in the state, con', 170, ''),
(47, 35, 'Italiensk for begynd', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2000-12-07', 74, 7, 'A group of strangers find friendship, family and love within an Italian beginners’ course.', 95, ''),
(48, 18, '봄 여름 가을 겨울 그리고 봄', 'https://image.tmdb.org/t/p/w500//6JDjZdFckZyMYgtawDwUb6HTwVp.jpg', 'movie', 'Released', '2003-09-19', 587, 8, 'An isolated lake, where an old monk lives in a small floating temple. The monk has a young boy living with him, learning to become a monk. We watch as seasons and years pass by.', 103, ''),
(49, 10749, 'Pretty Woman', 'https://image.tmdb.org/t/p/w500//3tuWpnCTe14zZZPt6sI1W9ByOXx.jpg', 'movie', 'Released', '1990-03-23', 4828, 7, 'When a millionaire wheeler-dealer enters a business contract with a Hollywood hooker Vivian Ward, he loses his heart in the bargain.', 119, ''),
(50, 35, 'The Big Lebowski', 'https://image.tmdb.org/t/p/w500//77ElMccPnTMPouRxSdbJ4nEjf69.jpg', 'movie', 'Released', '1998-03-06', 7170, 8, 'Jeffrey "The Dude" Lebowski, a Los Angeles slacker who only wants to bowl and drink White Russians, is mistaken for another Jeffrey Lebowski, a wheelchair-bound millionaire, and finds himself dragged into a strange series of events involving nihilists, ad', 117, ''),
(51, 18, 'Match Point', 'https://image.tmdb.org/t/p/w500//1HEdbjJ20vXn8nW1LwPMc5lY63U.jpg', 'movie', 'Released', '2005-10-26', 2708, 7, 'Match Point is Woody Allen’s satire of the British High Society and the ambition of a young tennis instructor to enter into it. Yet when he must decide between two women - one assuring him his place in high society, and the other that would take him far f', 124, ''),
(52, 12, 'The Lord of the Ring', 'https://image.tmdb.org/t/p/w500//vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg', 'movie', 'Released', '2001-12-18', 17245, 8, 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure tha', 178, ''),
(53, 12, 'The Lord of the Ring', 'https://image.tmdb.org/t/p/w500//9BUvLUz1GhbNpcyQRyZm1HNqMq4.jpg', 'movie', 'Released', '2002-12-18', 14855, 8, 'Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.', 179, ''),
(54, 18, 'Bez końca', 'https://image.tmdb.org/t/p/w500//xjcQI6O8xZCFtLVjp2IckYgDqV6.jpg', 'movie', 'Released', '1985-06-17', 29, 8, 'Taking place in a 1982 Poland a translator loses her husband and becomes a victim of her own sorrow. She looks to sex, to her son, to law, and to hypnotism when she has nothing else in this time of martial law when Solidarity was banned.', 108, ''),
(55, 99, 'Dworzec', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '1980-01-01', 14, 6, 'Railway Station is a documentary about a Warsaw railway station Dworzec that was controversial and against the government at the time. The footage that exposed the monitoring of sales was seized by police', 13, ''),
(56, 18, 'Krótki dzień pracy', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '1981-06-27', 3, 7, 'Kieślowski’s study of a political strike, controversially told from the viewpoint of a Communist functionary trying to keep order.', 73, ''),
(57, 12, 'もののけ姫', 'https://image.tmdb.org/t/p/w500//munffkEccvkGzuLwhLvRkTr9KAr.jpg', 'movie', 'Released', '1997-07-12', 4834, 8, 'Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to de', 134, ''),
(58, 16, '千と千尋の神隠し', 'https://image.tmdb.org/t/p/w500//Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg', 'movie', 'Released', '2001-07-20', 9688, 9, 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 125, ''),
(59, 99, 'Gimme Shelter', 'https://image.tmdb.org/t/p/w500//k74ezjZNmap2FpkxuO85NnWmcn.jpg', 'movie', 'Released', '1970-12-06', 84, 8, 'The landmark documentary about the tragically ill-fated Rolling Stones free concert at Altamont Speedway on December 6, 1969. Only four months earlier, Woodstock defined the Love Generation; now it lay in ruins on a desolate racetrack six miles outside of', 90, ''),
(60, 99, 'Primary', 'https://image.tmdb.org/t/p/w500//e6IPjjDzZDkgdkvxQtCjaVCMYJF.jpg', 'movie', 'Released', '1960-01-01', 19, 7, 'Primary is a documentary film about the primary elections between John F. Kennedy and Hubert Humphrey in 1960. Primary is the first documentary to use light equipment in order to follow their subjects in a more intimate filmmaking style. This unconvention', 60, ''),
(61, 99, 'Dont Look Back', 'https://image.tmdb.org/t/p/w500//1phzgB0vbLDYkimv9SDEYsEZjAn.jpg', 'movie', 'Released', '1967-05-17', 83, 8, 'In this wildly entertaining vision of one of the twentieth century’s greatest artists, Bob Dylan is surrounded by teen fans, gets into heated philosophical jousts with journalists, and kicks back with fellow musicians Joan Baez, Donovan, and Alan Price.', 96, ''),
(62, 10749, 'Groundhog Day', 'https://image.tmdb.org/t/p/w500//61dsn6ZsvI3BPNEHCQeDZeuhF7K.jpg', 'movie', 'Released', '1993-02-11', 4898, 8, 'A narcissistic T.V. weatherman, along with his attractive-but-distant producer and mawkish cameraman, is sent to report on Groundhog Day in the small town of Punxsutawney, where he finds himself repeating the same day over and over.', 101, ''),
(63, 18, 'Mifunes sidste sang', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '1999-03-12', 37, 7, 'Kresten, newly wed, is on the threshold of a great career success in his father-in-law´s company. But when the death of his own father takes him back to his poverty-stricken childhood home, far out in the country, his career plans fall apart. For one thin', 98, ''),
(64, 80, 'La mala educación', 'https://image.tmdb.org/t/p/w500//wNFiDhGnrnSfyqYxzeAa8mFnUhj.jpg', 'movie', 'Released', '2004-03-19', 534, 7, 'Two children, Ignacio and Enrique, know love, the movies and fear in a religious school at the beginning of the 1960s. Father Manolo, director of the school and its professor of literature, is witness to and part of these discoveries. The three are follow', 106, ''),
(65, 14, 'Donnie Darko', 'https://image.tmdb.org/t/p/w500//npVlvuV5UkUGcnjErXJ9AiUfECR.jpg', 'movie', 'Released', '2001-01-18', 8294, 8, 'After narrowly escaping a bizarre accident, a troubled teenager is plagued by visions of a large bunny rabbit that manipulates him to commit a series of crimes.', 114, ''),
(66, 18, 'All Quiet on the Wes', 'https://image.tmdb.org/t/p/w500//hSRb0YhB4TaeIKgZtQbFuY3l0XM.jpg', 'movie', 'Released', '1930-04-29', 379, 8, 'A young soldier faces profound disillusionment in the soul-destroying horror of World War I. Together with several other young German soldiers, he experiences the horrors of war, such evil of which he had not conceived of when signing up to fight. They ev', 133, ''),
(67, 18, 'Der Himmel über Berl', 'https://image.tmdb.org/t/p/w500//nIAT0K5vtkBfHTetVUsodqa9oc5.jpg', 'movie', 'Released', '1987-05-17', 651, 8, 'Two angels, Damiel and Cassiel, glide through the streets of Berlin, observing the bustling population, providing invisible rays of hope to the distressed but never interacting with them. When Damiel falls in love with lonely trapeze artist Marion, the an', 128, ''),
(68, 18, 'Les Quatre Cents Cou', 'https://image.tmdb.org/t/p/w500//4DLay7yf6KsSz6QpOtKbSqV7A1R.jpg', 'movie', 'Released', '1959-05-04', 1095, 8, 'For young Parisian boy Antoine Doinel, life is one difficult situation after another. Surrounded by inconsiderate adults, including his neglectful parents, Antoine spends his days with his best friend, Rene, trying to plan for a better life. When one of t', 99, ''),
(69, 18, 'The Secret Life of W', 'https://image.tmdb.org/t/p/w500//7eNnAuMW3jTi3DFFUv6XjEscgiN.jpg', 'movie', 'Released', '2005-12-15', 115, 7, 'A touching story of a deaf girl who is sent to an oil rig to take care of a man who has been blinded in a terrible accident. The girl has a special ability to communicate with the men on board and especially with her patient as they share intimate moments', 112, ''),
(70, 878, 'アキラ', 'https://image.tmdb.org/t/p/w500//qZ4NYuwME0j6QgJmIE6AZMgmCaj.jpg', 'movie', 'Released', '1988-07-16', 2127, 8, 'A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath that only two teenagers and a group of psychics can stop.', 124, ''),
(71, 53, '48 Hrs.', 'https://image.tmdb.org/t/p/w500//bKPvBwz0BfY9tx3jCWaYCBo3lq4.jpg', 'movie', 'Released', '1982-12-07', 813, 7, 'A hard-nosed cop reluctantly teams up with a wise-cracking criminal temporarily paroled to him, in order to track down a killer.', 96, ''),
(72, 878, 'Star Trek: The Motio', 'https://image.tmdb.org/t/p/w500//oQYpa1TKJRR58IrFGhppi9vL7PC.jpg', 'movie', 'Released', '1979-12-07', 1023, 6, 'When a destructive space entity is spotted approaching Earth, Admiral Kirk resumes command of the Starship Enterprise in order to intercept, examine, and hopefully stop it.', 132, ''),
(73, 28, 'Star Trek II: The Wr', 'https://image.tmdb.org/t/p/w500//9uUUey0emZQPDVczOJA2pe4SEMQ.jpg', 'movie', 'Released', '1982-06-04', 1186, 7, 'Admiral James T. Kirk is feeling old; the prospect of accompanying his old ship the Enterprise on a two week cadet cruise is not making him feel any younger. But the training cruise becomes a life or death struggle when Khan escapes from years of exile an', 113, ''),
(74, 18, 'The Dark Knight', 'https://image.tmdb.org/t/p/w500//cfT29Im5VDvjE0RpyKOSdCKZal7.jpg', 'movie', 'Released', '2008-07-16', 22585, 8, 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they so', 152, ''),
(75, 35, 'Wilbur begår selvmor', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2002-11-08', 50, 6, 'The strange comedy film of two close brothers; one, Wilbur, who wants to kill himself, and the other, Harbour, who tries to prevent this. When their father dies leaving them his bookstore they meet a woman who makes their lives a bit better yet with a bit', 111, ''),
(76, 35, 'Der bewegte Mann', 'https://image.tmdb.org/t/p/w500//1BMnXAAMbGN8N1xm2ZvlSVVUQiy.jpg', 'movie', 'Released', '1994-10-05', 57, 6, 'Der Bewegte Mann is a German comedy about a heterosexual man, Axel, who is thrown out of his girlfriends home for cheating and ends up moving in with a gay man. Axel learns the advantages of living with gay men even though they are attracted to him and wh', 90, ''),
(77, 14, 'Edward Scissorhands', 'https://image.tmdb.org/t/p/w500//3Nn5BOM1EVw1IYrv6MsbOS6N1Ol.jpg', 'movie', 'Released', '1990-12-05', 8924, 8, 'A small suburban town receives a visit from a castaway unfinished science experiment named Edward.', 105, ''),
(78, 12, 'Back to the Future P', 'https://image.tmdb.org/t/p/w500//skQN2UMQKQnOTmwplcYMx6ZF4jS.jpg', 'movie', 'Released', '1989-11-22', 8448, 8, 'Marty and Doc are at it again in this wacky sequel to the 1985 blockbuster as the time-traveling duo head to 2015 to nip some McFly family woes in the bud. But things go awry thanks to bully Biff Tannen and a pesky sports almanac. In a last-ditch attempt ', 108, ''),
(79, 18, 'La Boum', 'https://image.tmdb.org/t/p/w500//nwLfYHPSoI2A9OvdHF3TmFvcWZb.jpg', 'movie', 'Released', '1980-01-01', 723, 7, 'A thirteen-year-old French girl deals with moving to a new city and school in Paris, while at the same time her parents are getting a divorce.', 110, ''),
(80, 18, 'K-PAX', 'https://image.tmdb.org/t/p/w500//m9ELo5SDNZvp7CGbSVIMYBeY8wl.jpg', 'movie', 'Released', '2001-10-22', 1430, 7, 'Prot is a patient at a mental hospital who claims to be from a far away planet. His psychiatrist tries to help him, only to begin to doubt his own explanations.', 120, ''),
(81, 878, 'Predator 2', 'https://image.tmdb.org/t/p/w500//r0UGYPKBye5iHR2TF9FT5NuRpTF.jpg', 'movie', 'Released', '1990-11-20', 1714, 6, 'Ten years after a band of mercenaries first battled a vicious alien, the invisible creature from another world has returned to Earth—and this time, it’s drawn to the gang-ruled and ravaged city of Los Angeles. When it starts murdering drug dealers, detect', 108, ''),
(82, 35, 'La Boum 2', 'https://image.tmdb.org/t/p/w500//3oNDTUxv2lLWMqt5R12A0vM5dBn.jpg', 'movie', 'Released', '1982-12-08', 414, 6, 'A young French teenage girl after moving to a new city falls in love with a boy and is thinking of having sex with him because her girlfriends have already done it.', 109, ''),
(83, 12, '20,000 Leagues Under', 'https://image.tmdb.org/t/p/w500//pIBZpX9H6U6Nk6gbyWTD4rFKEqq.jpg', 'movie', 'Released', '1954-05-13', 425, 7, 'A ship sent to investigate a wave of mysterious sinkings encounters the advanced submarine, the Nautilus, commanded by Captain Nemo.', 127, ''),
(84, 878, 'Star Trek VI: The Un', 'https://image.tmdb.org/t/p/w500//vfo2dzdXnoArYwrkM7kw1vgb7dL.jpg', 'movie', 'Released', '1991-12-06', 745, 7, 'On the eve of retirement, Kirk and McCoy are charged with assassinating the Klingon High Chancellor and imprisoned. The Enterprise crew must help them escape to thwart a conspiracy aimed at sabotaging the last best hope for peace.', 113, ''),
(85, 12, 'Le Grand Bleu', 'https://image.tmdb.org/t/p/w500//vXnJ1efTZKXDjnY5eMae3lz9CS7.jpg', 'movie', 'Released', '1988-05-11', 851, 8, 'Two men answer the call of the ocean in this romantic fantasy-adventure.  Jacques and Enzo are a pair of friends who have been close since childhood, and who share a passion for the dangerous sport of free diving. Professional diver Jacques opted to follo', 168, ''),
(86, 27, 'Saw', 'https://image.tmdb.org/t/p/w500//qtWjZgCmslPwjP4DFUcLBUj13GV.jpg', 'movie', 'Released', '2004-10-01', 5804, 7, 'Obsessed with teaching his victims the value of life, a deranged, sadistic serial killer abducts the morally wayward. Once captured, they must face impossible choices in a horrific game of survival. The victims must fight to win their lives back, or die t', 103, ''),
(87, 35, 'The Fisher King', 'https://image.tmdb.org/t/p/w500//g4DAuZVte21KImR2FJN82k1pD1J.jpg', 'movie', 'Released', '1991-09-09', 771, 7, 'Two troubled men face their terrible destinies and events of their past as they join together on a mission to find the Holy Grail and thus to save themselves.', 138, ''),
(88, 53, 'Blown Away', 'https://image.tmdb.org/t/p/w500//fmSeUzAcBPOBXeaJIQ11hACwfsj.jpg', 'movie', 'Released', '1994-07-01', 273, 6, 'Blown Away tells the story of Jimmy Dove who works for the Boston bomb squad. Shortly after Dove leaves the force his partner is killed by a bomb that Dove thinks might have been made by someone he knows.', 121, ''),
(89, 80, 'The Interpreter', 'https://image.tmdb.org/t/p/w500//A5mBIAtZOqVpAVUXolwtOnaQcZc.jpg', 'movie', 'Released', '2005-04-08', 849, 6, 'After Silvia Broome, an interpreter at United Nations headquarters, overhears plans of an assassination, an American Secret Service agent is sent to investigate.', 128, ''),
(90, 18, 'The Good German', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2006-12-08', 176, 6, 'An American journalist arrives in Berlin just after the end of World War Two. He becomes involved in a murder mystery surrounding a dead GI who washes up at a lakeside mansion during the Potsdam negotiations between the Allied powers. Soon his investigati', 108, ''),
(91, 12, 'The Wizard', 'https://image.tmdb.org/t/p/w500//xTLRUzWK7hpC5cdwCAqNaWIUkwi.jpg', 'movie', 'Released', '1989-12-15', 191, 6, 'Corey refuses to let his emotionally disturbed younger brother Jimmy be institutionalized, and the two run away together. They soon join forces with a resourceful girl, who notices that Jimmy has a special talent: he is a "wizard" at video games and can a', 100, ''),
(92, 80, 'Jackie Brown', 'https://image.tmdb.org/t/p/w500//lXnsC7wRDLccJR3Ju4nInvLiKO.jpg', 'movie', 'Released', '1997-04-10', 4022, 7, 'Jackie Brown is a flight attendant who gets caught in the middle of smuggling cash into the country for her gunrunner boss. When the cops try to use Jackie to get to her boss, she hatches a plan — with help from a bail bondsman — to keep the money for her', 154, ''),
(93, 18, 'Lucky Number Slevin', 'https://image.tmdb.org/t/p/w500//x0O0LaHRqmgz5FVOD1fQgsJg2un.jpg', 'movie', 'Released', '2006-02-24', 2682, 8, 'Slevin is mistakenly put in the middle of a personal war between the city’s biggest criminal bosses. Under constant watch, Slevin must try not to get killed by an infamous assassin and come up with an idea of how to get out of his current dilemma. A film ', 110, ''),
(94, 28, 'Sin City', 'https://image.tmdb.org/t/p/w500//h7EkLFDAQGrebhooz1G6qZenQFl.jpg', 'movie', 'Released', '2005-04-01', 5485, 7, 'Welcome to Sin City. This town beckons to the tough, the corrupt, the brokenhearted. Some call it dark… Hard-boiled. Then there are those who call it home — Crooked cops, sexy dames, desperate vigilantes. Some are seeking revenge, others lust after redemp', 124, ''),
(95, 99, 'Das Dorf der Freunds', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2001-08-25', 1, 10, 'A German Documentary about the “village of friendship” that was created by American Veteran George Mizo to help the Vietnamese kids suffering from the Vietnam War.', 52, ''),
(96, 18, 'Die innere Sicherhei', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2000-09-01', 18, 7, 'With 1970s Germany in the background, this film depicts the story of a family from the “R.A.F. Terrorist” group and their search for a normal life and their inner self.', 106, ''),
(97, 12, 'Back to the Future P', 'https://image.tmdb.org/t/p/w500//nh6mrOtIvD8MMC6JQIzwNDZi2G0.jpg', 'movie', 'Released', '1990-05-25', 6750, 7, 'The final installment of the Back to the Future trilogy finds Marty digging the trusty DeLorean out of a mineshaft and looking for Doc in the Wild West of 1885. But when their time machine breaks down, the travelers are stranded in a land of spurs. More p', 118, ''),
(98, 878, 'Star Trek: First Con', 'https://image.tmdb.org/t/p/w500//13zoJs9NYW3mtqncZUOucUIVs7r.jpg', 'movie', 'Released', '1996-11-22', 1094, 7, 'The Borg, a relentless race of cyborgs, are on a direct course for Earth. Violating orders to stay away from the battle, Captain Picard and the crew of the newly-commissioned USS Enterprise E pursue the Borg back in time to prevent the invaders from chang', 111, ''),
(99, 878, 'Star Trek: Nemesis', 'https://image.tmdb.org/t/p/w500//dQozRrhhXAdrFBFMTwpC6PnSMmK.jpg', 'movie', 'Released', '2002-12-13', 855, 6, 'En route to the honeymoon of William Riker to Deanna Troi on her home planet of Betazed, Captain Jean-Luc Picard and the crew of the U.S.S. Enterprise receives word from Starfleet that a coup has resulted in the installation of a new Romulan political lea', 117, ''),
(100, 18, 'Mean Streets', 'https://image.tmdb.org/t/p/w500//QBb91Qr4TbBq0t3F5A4XU3Uwaj.jpg', 'movie', 'Released', '1973-10-02', 1217, 7, 'A small-time hood must choose from among love, friendship and the chance to rise within the mob.', 110, ''),
(101, 18, 'Le Salaire de la peu', 'https://image.tmdb.org/t/p/w500//sdNPipjZoOJFuTBwH8EyEb5dsKv.jpg', 'movie', 'Released', '1953-04-21', 434, 8, 'In the South American jungle, supplies of nitroglycerine are needed at a remote oil field. The oil company pays four men to deliver the supplies in two trucks. A tense rivalry develops between the two sets of drivers on the rough remote roads where the sl', 153, ''),
(102, 18, 'Hotel Rwanda', 'https://image.tmdb.org/t/p/w500//cZBwAJiA8O6SKYzT2Vq4c8qJoHP.jpg', 'movie', 'Released', '2004-03-04', 1753, 8, 'Inspired by true events, this film takes place in Rwanda in the 1990s when more than a million Tutsis were killed in a genocide that went mostly unnoticed by the rest of the world. Hotel owner Paul Rusesabagina houses over a thousand refuges in his hotel ', 122, ''),
(103, 18, 'Paradise Found', 'https://image.tmdb.org/t/p/w500//nwbbZhrIXW4YHrn3YDn9pBA19eO.jpg', 'movie', 'Released', '2003-01-01', 11, 7, 'Paradise Found is a biography about the painter Paul Gauguin. Focusing on his personal conflict between citizen life and his family life and the art scene in Frane. In an incredible imagery montage Gauguin manages to make a successful living in the South ', 89, ''),
(104, 18, 'Dead Poets Society', 'https://image.tmdb.org/t/p/w500//tJRToZBfb52NhF6SMGAe0bWQc6z.jpg', 'movie', 'Released', '1989-06-02', 7201, 8, 'At an elite, old-fashioned boarding school in New England, a passionate English teacher inspires his students to rebel against convention and seize the potential of every day, courting the disdain of the stern headmaster.', 128, ''),
(105, 35, 'Berlin is in Germany', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2001-11-01', 6, 6, 'When Martin, a former GDR citizen, is released from jail, he lately becomes confronted with the consequences of the German re-unification.', 97, ''),
(106, 9648, 'North by Northwest', 'https://image.tmdb.org/t/p/w500//uL7nTO46KAup4bkYmz1A3on036B.jpg', 'movie', 'Released', '1959-07-08', 2401, 8, 'Advertising man Roger Thornhill is mistaken for a spy, triggering a deadly cross-country chase.', 136, ''),
(107, 27, 'Saw III', 'https://image.tmdb.org/t/p/w500//kquJm3gXnMxKQyDTpoCrwWROzmI.jpg', 'movie', 'Released', '2006-10-27', 2735, 6, 'Jigsaw has disappeared. Along with his new apprentice Amanda, the puppet-master behind the cruel, intricate games that have terrified a community and baffled police has once again eluded capture and vanished. While city detective scramble to locate him, D', 114, ''),
(108, 28, 'The Terminator', 'https://image.tmdb.org/t/p/w500//wh4ze6klUbeichAj603OKZwY1W5.jpg', 'movie', 'Released', '1984-10-26', 8337, 8, 'In the post-apocalyptic future, reigning tyrannical supercomputers teleport a cyborg assassin known as the "Terminator" back to 1984 to kill Sarah Connor, whose unborn son is destined to lead insurgents against 21st century mechanical hegemony. Meanwhile,', 108, ''),
(109, 18, 'East of Eden', 'https://image.tmdb.org/t/p/w500//u7i1XtbOubq0xwRy2Zbgmox6g9W.jpg', 'movie', 'Released', '1955-03-09', 403, 8, 'In the Salinas Valley, in and around World War I, Cal Trask feels he must compete against overwhelming odds with his brother for the love of their father. Cal is frustrated at every turn, from his reaction to the war, to how to get ahead in business and i', 115, ''),
(110, 18, 'Rebecca', 'https://image.tmdb.org/t/p/w500//jKgLVAhoq4fXBs1C9Gjvap93fxd.jpg', 'movie', 'Released', '1940-03-23', 861, 8, 'Story of a young woman who marries a fascinating widower only to find out that she must live in the shadow of his former wife, Rebecca, who died mysteriously several years earlier. The young wife must come to grips with the terrible secret of her handsome', 130, ''),
(111, 18, 'Człowiek z marmuru', 'https://image.tmdb.org/t/p/w500//uhRvvv5wSZfHiTtrL7IpCIHM4No.jpg', 'movie', 'Released', '1977-02-25', 36, 7, 'Man of Marble is a Polish film about a student making a film about a bricklayer who was once idolized. She interviews people who knew him and finds old footage that lead to an unfolding mystery that causes her producer to cancel the project.', 165, ''),
(112, 18, 'Człowiek z żelaza', 'https://image.tmdb.org/t/p/w500//rbvrfkc1fKbpWZGYIUgO8v4vNLH.jpg', 'movie', 'Released', '1981-07-27', 29, 7, 'In Warsaw in 1980, the Communist Party sends Winkel, a weak, alcoholic TV hack, to Gdansk to dig up dirt on the shipyard strikers, particularly on Maciek Tomczyk, an articulate worker whose father was killed in the December 1970 protests. Posing as sympat', 147, ''),
(113, 80, 'The Outsiders', 'https://image.tmdb.org/t/p/w500//zE4QhjqT7Nr9Y0LPYaPtKHhM3GR.jpg', 'movie', 'Released', '1983-03-25', 709, 7, 'When two poor greasers, Johnny, and Ponyboy are assaulted by a vicious gang, the socs, and Johnny kills one of the attackers, tension begins to mount between the two rival gangs, setting off a turbulent chain of events.', 91, ''),
(114, 18, 'Der blaue Engel', 'https://image.tmdb.org/t/p/w500//jLvlD6ABDESFfYl3F1TqCoiBaig.jpg', 'movie', 'Released', '1930-04-01', 155, 7, 'Prim professor Immanuel Rath finds some of his students ogling racy photos of cabaret performer Lola Lola and visits a local club, The Blue Angel, in an attempt to catch them there. Seeing Lola perform, the teacher is filled with lust, eventually resignin', 108, ''),
(115, 18, 'Syriana', 'https://image.tmdb.org/t/p/w500//8bEagsrYdl3NXnSfp5bSZ5kj834.jpg', 'movie', 'Released', '2005-11-23', 841, 6, 'The Middle Eastern oil industry is the backdrop of this tense drama, which weaves together numerous story lines. Bennett Holiday is an American lawyer in charge of facilitating a dubious merger of oil companies, while Bryan Woodman, a Switzerland-based en', 128, ''),
(116, 18, 'Das Cabinet des Dr. ', 'https://image.tmdb.org/t/p/w500//m0N89MIIu6qYZcujCRzBHrkZbns.jpg', 'movie', 'Released', '1920-02-27', 752, 8, 'Francis, a young man, recalls in his memory the horrible experiences he and his fiancée Jane recently went through. Francis and his friend Alan visit The Cabinet of Dr. Caligari, an exhibit where the mysterious doctor shows the somnambulist Cesare, and aw', 77, ''),
(117, 18, 'The Godfather', 'https://image.tmdb.org/t/p/w500//ejdD20cdHNFAYAN2DlqPToXKyzx.jpg', 'movie', 'Released', '1972-03-14', 12496, 9, 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would', 175, ''),
(118, 35, 'Some Like It Hot', 'https://image.tmdb.org/t/p/w500//m7v4Qi1y7UFgMZn2sIWoTXDpYSu.jpg', 'movie', 'Released', '1959-03-19', 2015, 8, 'Two musicians witness a mob hit and struggle to find a way out of the city before they are found by the gangsters. Their only opportunity is to join an all-girl band as they leave on a tour. To make their getaway they must first disguise themselves as wom', 122, ''),
(119, 18, 'The Godfather: Part ', 'https://image.tmdb.org/t/p/w500//poec6RqOKY9iSiIUmfyfPfiLtvB.jpg', 'movie', 'Released', '1974-12-20', 7412, 9, 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 202, ''),
(120, 80, 'Natural Born Killers', 'https://image.tmdb.org/t/p/w500//kE8Wsg0FqHvYuwNijv9jbi8FGHw.jpg', 'movie', 'Released', '1994-08-25', 2061, 7, 'Two victims of traumatized childhoods become lovers and psychopathic serial murderers irresponsibly glorified by the mass media.', 119, ''),
(121, 80, 'The Godfather: Part ', 'https://image.tmdb.org/t/p/w500//mm6ex61CAcRCgd4ua0IZ3wAx0qW.jpg', 'movie', 'Released', '1990-12-24', 3729, 7, 'In the midst of trying to legitimize his business dealings in 1979 New York and Italy, aging mafia don, Michael Corleone seeks forgiveness for his sins while taking a young protege under his wing.', 162, ''),
(122, 12, 'King Kong', 'https://image.tmdb.org/t/p/w500//7hDdW3C17pi4MdSeYXs8bwIVA78.jpg', 'movie', 'Released', '1933-03-15', 795, 8, 'A film crew discovers the "eighth wonder of the world," a giant prehistoric ape, and brings him back to New York, where he wreaks havoc.', 104, ''),
(123, 80, 'The Killing', 'https://image.tmdb.org/t/p/w500//dqDwLSs99aWOpu969SLSjxm9Hhp.jpg', 'movie', 'Released', '1956-06-06', 798, 8, 'Career criminal Johnny Clay recruits a sharpshooter, a crooked police officer, a bartender and a betting teller named George, among others, for one last job before he goes straight and gets married. But when George tells his restless wife about the scheme', 85, ''),
(124, 28, 'I Kina spiser de hun', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '1999-09-10', 145, 7, 'An intent fast paced Danish dark comedy film about two separately motivated brothers who with their slightly psychopathic tendencies end up in a touchy situation. One brother gets in serious trouble after a bank robbery and begs the other brother for help', 91, ''),
(125, 10751, 'Willy Wonka & the Ch', 'https://image.tmdb.org/t/p/w500//iiusvOLB4ytkZ6FSFMlGHvt33uW.jpg', 'movie', 'Released', '1971-06-29', 2023, 8, 'Eccentric candy man Willy Wonka prompts a worldwide frenzy when he announces that golden tickets hidden inside five of his delicious candy bars will admit their lucky holders into his top-secret confectionary. But does Wonka have an agenda hidden amid a w', 100, ''),
(126, 12, 'Live and Let Die', 'https://image.tmdb.org/t/p/w500//v28YYcN5p9hD8PKGAeWLz0ugsfX.jpg', 'movie', 'Released', '1973-07-05', 1132, 7, 'James Bond must investigate a mysterious murder case of a British agent in New Orleans. Soon he finds himself up against a gangster boss named Mr. Big.', 121, ''),
(127, 12, 'King Kong', 'https://image.tmdb.org/t/p/w500//mRM2NB0i3wv4HqxXvwIjEVi4Qqq.jpg', 'movie', 'Released', '2005-12-12', 5201, 7, 'In 1933 New York, an overly ambitious movie producer coerces his cast and hired ship crew to travel to mysterious Skull Island, where they encounter Kong, a giant ape who is immediately smitten with the leading lady.', 187, ''),
(128, 18, 'Antoine et Colette', 'https://image.tmdb.org/t/p/w500//ymtwNtiuZwbYa1Vetp68VOGgrw3.jpg', 'movie', 'Released', '1962-06-22', 105, 7, 'Now aged 17, Antoine Doinel works in a factory which makes records. At a music concert, he meets a girl his own age, Colette, and falls in love with her. Later, Antoine goes to extraordinary lengths to please his new girlfriend and her parents, but Colett', 32, ''),
(129, 80, 'Oliver Twist', 'https://image.tmdb.org/t/p/w500//pP3fTbqsvpr9p0fc5tr7tJkdZqb.jpg', 'movie', 'Released', '2005-09-23', 794, 7, 'Oliver Twist the modern filmed version of Charles Dickens bestseller, a Roman Polanski adaptation. The classic Dickens tale, where an orphan meets a pickpocket on the streets of London. From there, he joins a household of boys who are trained to steal for', 130, ''),
(130, 28, 'The 39 Steps', 'https://image.tmdb.org/t/p/w500//gCzICz8GbAOghIZGRBDT6GZhwgS.jpg', 'movie', 'Released', '1935-06-06', 499, 7, 'Richard Hannay stumbles upon a conspiracy that thrusts him into a hectic chase across the Scottish moors—a chase in which he is both the pursuer and the pursued—as well as into an unexpected romance with the cool Pamela.', 86, ''),
(131, 18, 'Cat on a Hot Tin Roo', 'https://image.tmdb.org/t/p/w500//o53YZOxru84Z9wgZwbwqF25bdOl.jpg', 'movie', 'Released', '1958-09-20', 408, 8, 'An alcoholic ex-football player drinks his days away, having failed to come to terms with his sexuality and his real feelings for his football buddy who died after an ambiguous accident. His wife is crucified by her desperation to make him desire her: but', 108, ''),
(132, 35, 'The King of Comedy', 'https://image.tmdb.org/t/p/w500//s0hhtvMN1QBrMVYvmiB6uzK5sHf.jpg', 'movie', 'Released', '1982-12-18', 1159, 8, 'Aspiring comic Rupert Pupkin attempts to achieve success in show business by stalking his idol, a late night talk-show host who craves his own privacy.', 109, ''),
(133, 18, 'Le Mépris', 'https://image.tmdb.org/t/p/w500//vcwVpHrPCatk76rtV2u6P8XGy9n.jpg', 'movie', 'Released', '1963-10-29', 392, 7, 'A philistine in the art film business, Jeremy Prokosch is a producer unhappy with the work of his director. Prokosch has hired Fritz Lang (as himself) to direct an adaptation of "The Odyssey," but when it seems that the legendary filmmaker is making a pic', 103, ''),
(134, 18, 'Carne trémula', 'https://image.tmdb.org/t/p/w500//xg6wXs16dZqWbAxIDNJVpT70Ymu.jpg', 'movie', 'Released', '1997-10-28', 293, 7, 'A scorned ex-convict forces himself into the lives of the couple who put him behind bars.', 103, ''),
(135, 18, 'À bout de souffle', 'https://image.tmdb.org/t/p/w500//gCC23I8h33PpZ1qdYtYLMVnEkwI.jpg', 'movie', 'Released', '1960-03-16', 921, 8, 'A young car thief kills a policeman and tries to persuade a girl to hide in Italy with him.', 90, ''),
(136, 35, 'Wir sagen Du! Schatz', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2007-11-01', 3, 4, 'Oliver doesn’t have a family so he steals one.', 98, ''),
(137, 28, 'Batman Begins', 'https://image.tmdb.org/t/p/w500//lh5lbisD4oDbEKgUxoRaZU8HVrk.jpg', 'movie', 'Released', '2005-06-10', 14507, 8, 'Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld', 140, ''),
(138, 18, 'Das weisse Rauschen', 'https://image.tmdb.org/t/p/w500/', 'movie', 'Released', '2001-12-31', 33, 7, 'Lukas, a young schizophrenic man, has to deal with a new town, a new relationship, and the paranoia in his head.', 107, ''),
(139, 18, 'Die fetten Jahre sin', 'https://image.tmdb.org/t/p/w500//3qt50ZKfBWsRKtPfpJFjeTLCIWc.jpg', 'movie', 'Released', '2004-10-25', 199, 7, 'Three activists cobble together a kidnapping plot after they encounter a businessman in his home.', 127, '');
INSERT INTO `media` (`id`, `genre_id`, `title`, `picture`, `type`, `status`, `release_date`, `vote_count`, `vote_avertage`, `summary`, `runtime`, `trailer_url`) VALUES
(140, 18, 'The Shawshank Redemp', 'https://image.tmdb.org/t/p/w500//avedvodAZUcwqevBfm8p4G2NziQ.jpg', 'movie', 'Released', '1994-09-23', 16546, 9, 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne c', 142, ''),
(141, 18, 'Amadeus', 'https://image.tmdb.org/t/p/w500//yySl5IaSwbzyakOxmURfaQh0BoO.jpg', 'movie', 'Released', '1984-09-06', 2586, 8, 'The incredible story of genius musician Wolfgang Amadeus Mozart, told in flashback by his peer and secret rival, Antonio Salieri—now confined to an insane asylum.', 160, ''),
(142, 28, 'Terminator 2: Judgme', 'https://image.tmdb.org/t/p/w500//umaoScaCsfl9g2dyrXrvMPp59Q7.jpg', 'movie', 'Released', '1991-07-03', 8150, 8, 'Nearly 10 years have passed since Sarah Connor was targeted for termination by a cyborg from the future. Now her son, John, the future leader of the resistance, is the target for a newer, more deadly terminator. Once again, the resistance has managed to s', 156, ''),
(143, 80, 'Strange Days', 'https://image.tmdb.org/t/p/w500//kAl96eiG6Z83sHTfSqrHyBKtl3g.jpg', 'movie', 'Released', '1995-10-13', 727, 7, 'Set in the year 1999 during the last days of the old millennium, the movie tells the story of Lenny Nero, an ex-cop who now deals with data-discs containing recorded memories and emotions. One day he receives a disc which contains the memories of a murder', 145, ''),
(144, 99, 'Deutschland. Ein Som', 'https://image.tmdb.org/t/p/w500//fy9DOJO07EaVun1HcGdjFAVdtkt.jpg', 'movie', 'Released', '2006-10-03', 32, 7, 'A documentary of the German national soccer team’s 2006 World Cup experience that changed the face of modern Germany.', 110, ''),
(145, 35, 'Bull Durham', 'https://image.tmdb.org/t/p/w500//cNmwu1YnnsvRIMGR7pZRQ4zdlAj.jpg', 'movie', 'Released', '1988-06-15', 325, 7, 'Veteran catcher Crash Davis is brought to the minor league Durham Bulls to help their up and coming pitching prospect, "Nuke" Laloosh. Their relationship gets off to a rocky start and is further complicated when baseball groupie Annie Savoy sets her sight', 108, ''),
(146, 37, 'High Noon', 'https://image.tmdb.org/t/p/w500//6S4gjpkd359UuMLfrnUV1M695DF.jpg', 'movie', 'Released', '1952-06-09', 811, 8, 'Will Kane, the sheriff of a small town in New Mexico, learns a notorious outlaw he put in jail has been freed, and will be arriving on the noon train. Knowing the outlaw and his gang are coming to kill him, Kane is determined to stand his ground, so he ga', 85, ''),
(147, 18, 'Casablanca', 'https://image.tmdb.org/t/p/w500//wOfzdzC0QZyhUIlyjeMuUYSb8Ax.jpg', 'movie', 'Released', '1942-11-26', 3172, 8, 'In Casablanca, Morocco in December 1941, a cynical American expatriate meets a former lover, with unforeseen complications.', 102, ''),
(148, 35, 'Barton Fink', 'https://image.tmdb.org/t/p/w500//dTqnSdX7YQH6drivgOYrIJ5gzrz.jpg', 'movie', 'Released', '1991-08-01', 971, 8, 'A renowned New York playwright is enticed to California to write for the movies and discovers the hellish truth of Hollywood.', 116, ''),
(149, 99, 'Riding Giants', 'https://image.tmdb.org/t/p/w500//6B3kS8PeYG06VAEvRWHDsvp6Fjz.jpg', 'movie', 'Released', '2004-07-09', 30, 8, 'Riding Giants is story about big wave surfers who have become heroes and legends in their sport. Directed by the skateboard guru Stacy Peralta.', 105, ''),
(150, 18, 'Desert Hearts', 'https://image.tmdb.org/t/p/w500//tIFRPjIXQ3sYrmxbIeOu9K1JkUz.jpg', 'movie', 'Released', '1985-10-01', 70, 7, 'The story of straight-edge literature professor Vivian who travels to Reno to get away from a relationship breakup when she falls in love with an attractive and unconventional girl named Cay.', 91, '');

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(80) NOT NULL,
  `password` varchar(80) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Contenu de la table `user`
--

INSERT INTO `user` (`id`, `email`, `password`) VALUES
(1, 'coding@gmail.com', '123456');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
